FROM centos:centos7

MAINTAINER TeamCloudYuga <ved@cloudyuga.guru>

RUN mkdir /tmp/copywork

ADD current-file /tmp/work/

ADD current-tar-gz.tar.gz /tmp/work/

ADD current-tar.tar /tmp/work/

ADD current-zip.zip /tmp/work/
