FROM centos:centos7

MAINTAINER TeamCloudYuga <ved@cloudyuga.guru>

RUN mkdir /tmp/copywork

COPY current-file /tmp/work/

COPY current-tar-gz.tar.gz /tmp/work/

COPY current-tar.tar /tmp/work/

COPY current-zip.zip /tmp/work/
